# Resource Optimization Configuration
vm_optimization:
  rightsizing:
    # CPU utilization thresholds
    cpu:
      underutilized:
        threshold: 20  # percentage
        duration: 14  # days
      overutilized:
        threshold: 80
        duration: 7
    
    # Memory utilization thresholds
    memory:
      underutilized:
        threshold: 30
        duration: 14
      overutilized:
        threshold: 85
        duration: 7
    
    # Recommendations
    recommendations:
      min_savings: 50  # USD per month
      risk_tolerance: "medium"  # low, medium, high
      excluded_vms:
        - "prod-critical-*"
        - "compliance-*"

  spot_instances:
    target_savings: 60  # percentage
    max_interruption_rate: 10  # percentage
    suitable_workloads:
      - "batch-processing"
      - "dev-test"
      - "ci-cd"

storage_optimization:
  unused_resources:
    # Detect unused disks
    disks:
      unused_threshold_days: 30
      exclude_patterns:
        - "*-backup"
        - "*-archive"
    
    # Detect unused snapshots
    snapshots:
      retention_days: 90
      exclude_patterns:
        - "backup-*"
        - "golden-image-*"

  tier_optimization:
    # Storage account tier optimization
    storage_accounts:
      analysis_period_days: 90
      min_savings_threshold: 100  # USD
      access_pattern_analysis: true
    
    # Managed disk tier optimization
    managed_disks:
      iops_analysis_period_days: 30
      throughput_analysis_period_days: 30
      min_savings_threshold: 50  # USD

network_optimization:
  # Load balancer optimization
  load_balancers:
    usage_threshold: 40  # percentage
    analysis_period_days: 30
  
  # Reserved bandwidth optimization
  bandwidth:
    utilization_threshold: 60  # percentage
    forecast_period_months: 6
    min_savings_threshold: 200  # USD
